Script started on 2016年03月09日 (週三) 15時32分06秒
]0;F74004101@2015cpp: ~/PD2F74004101@2015cpp:~/PD2$ cat timr[Ker2.,c[K[Kcpp
#include <iostream>
#include <string>
using namespace std;

class Timer{
	public:
	//the member function hello with parameter name
	void hello(string name)
	{
		cout<<"Hello"<<name<<"!"<<endl;
	}

};

int main()
{
	Timer tmr;//create the object
	string username;//the variable temporarily storing the username
	cout<<"Please enter your name:";
	getline(cin,username);
	tmr.hello(username);
	return 0;
}
]0;F74004101@2015cpp: ~/PD2F74004101@2015cpp:~/PD2$ g++ -o timer2 timer2.cpp
]0;F74004101@2015cpp: ~/PD2F74004101@2015cpp:~/PD2$ l[K./timer2
Please enter your name:csienbe   bear
Hellocsiebear!
]0;F74004101@2015cpp: ~/PD2F74004101@2015cpp:~/PD2$ exit

Script done on 2016年03月09日 (週三) 15時32分38秒
