Script started on 2016年03月09日 (週三) 15時50分45秒
c]0;F74004101@2015cpp: ~/PD2/course/w2F74004101@2015cpp:~/PD2/course/w2$ cat[K[K[Kcat timer.[K2.cpp
#include <iostream>
#include <string>
using namespace std;

class Timer{
	public:
	//the member function hello with parameter name
	void hello(string name)
	{
		cout<<"Hello"<<name<<"!"<<endl;
	}

};

int main()
{
	Timer tmr;//create the object
	string username;//the variable temporarily storing the username
	cout<<"Please enter your name:";
	getline(cin,username);
	tmr.hello(username);
	return 0;
}
]0;F74004101@2015cpp: ~/PD2/course/w2F74004101@2015cpp:~/PD2/course/w2$ g++ -o timer2 timer2.cpp
]0;F74004101@2015cpp: ~/PD2/course/w2F74004101@2015cpp:~/PD2/course/w2$ ./timer2
Please enter your name:123   李碩軒
Hello李碩軒!
]0;F74004101@2015cpp: ~/PD2/course/w2F74004101@2015cpp:~/PD2/course/w2$ ./timer2
Please enter your name:104 李碩軒(測試空白)
Hello104 李碩軒(測試空白)!
]0;F74004101@2015cpp: ~/PD2/course/w2F74004101@2015cpp:~/PD2/course/w2$ ./timer2g++ -o timer2 timer2.cpp[16P./timer2
Please enter your name:104	李碩軒(測試tab)
Hello104	李碩軒(測試tab)!
]0;F74004101@2015cpp: ~/PD2/course/w2F74004101@2015cpp:~/PD2/course/w2$ exit

Script done on 2016年03月09日 (週三) 15時51分45秒
